# Generated by Django 3.2.7 on 2021-09-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('rate', models.IntegerField(verbose_name='Rate')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('photo', models.ImageField(upload_to='foodsPic', verbose_name='Photo')),
                ('time', models.IntegerField(verbose_name='Bake time')),
                ('add_time', models.IntegerField(verbose_name='Add time')),
            ],
        ),
    ]
