# Generated by Django 3.2.7 on 2021-09-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.PositiveIntegerField(verbose_name='Bake time'),
        ),
    ]
