# Generated by Django 3.2.7 on 2021-09-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20210913_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
