# Generated by Django 3.2.7 on 2021-09-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_alter_food_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.IntegerField(choices=[(0, 'Select item'), (1, 'Drink'), (2, 'Lunch'), (3, 'Dinner')], default=0, verbose_name='Category'),
        ),
    ]
