# Generated by Django 3.2.7 on 2021-09-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='summeryDes',
            field=models.CharField(default='', max_length=250, verbose_name='Summery Description'),
        ),
    ]
