# Generated by Django 3.2.7 on 2021-09-19 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_food_summerydes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food', verbose_name='Comment')),
            ],
        ),
    ]
