# Generated by Django 3.2.7 on 2021-09-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.AddField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Date and Time'),
        ),
    ]
