# Generated by Django 3.2.7 on 2021-09-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_auto_20210919_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and Time'),
        ),
    ]
